env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
overrides:
  - files:
    - backend/**.js
    parserOptions:
      sourceType: script
plugins:
  - react
settings:
  react:
    version: '16.10'
rules:
  no-unused-vars:
    - off
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  block-spacing:
    - warn
    - always
  object-curly-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - never
  no-var:
    - warn
  no-trailing-spaces:
    - warn
  no-whitespace-before-property:
    - warn
  semi-spacing:
    - warn
  semi-style:
    - warn
  space-in-parens:
    - warn
    - never
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - never
  space-unary-ops:
    - warn
  spaced-comment:
    - warn
    - always
  comma-spacing:
    - warn
  comma-style:
    - warn
    - last
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  key-spacing:
    - warn
  eqeqeq:
    - warn
  react/prop-types:
    - off