env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  object-curly-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - never