env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: script
overrides:
  - files:
    - backend/**.js
    parserOptions:
      sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  block-spacing:
    - warn
    - always
  object-curly-spacing:
    - warn
    - always
  array-bracket-spacing:
    - warn
    - never
  no-var:
    - warn
  no-trailing-spaces:
    - warn
  no-whitespace-before-property:
    - warn
  semi-spacing:
    - warn
  semi-style:
    - warn
  space-in-parens:
    - warn
    - never
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - never
  space-unary-ops:
    - warn
  spaced-comment:
    - warn
    - always
  comma-spacing:
    - warn
  comma-style:
    - warn
    - last
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true