env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  react:
    version: '16.5'
rules:
  indent:
    - warn
    - 2
  react/prop-types:
    - off
  no-useless-escape:
    - off
